local _M = {}
_M.KIND_ID = 1009
_M.GAME_PLAYER = 1
_M.GAME_NAME = "金瓶梅"
_M.GS_ST_FREE = GameDefine.GAME_STATUS_FREE
_M.GS_ST_PLAY = GameDefine.GAME_STATUS_PLAY

_M.STATUS_BLACK = 0
_M.STATUS_WHITE = 1
_M.STATUS_NORMAL = -1

_M.SERVER_LEN = 32

_M.SUB_S_CARD_SCROLL = 101
_M.SUB_S_MESSAGE_INFO = 102

_M.SUB_C_CARD_SCROLL = 1
_M.SUB_C_BONUS_SCROLL = 2

return _M

